# Generated by Django 5.0.2 on 2024-02-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='query',
        ),
    ]
